In [1]:
import numpy as np

In [2]:
myMatrix1 = np.array([[1, 4], [5, 3]])
print(myMatrix1)

[[1 4]
 [5 3]]


In [ ]:
myMatrix2 = np.array([[1, 3], [5, 6]])
myMatrix3 = 3*myMatrix1 - 4*myMatrix2
print(myMatrix3)

[[ -1   0]
 [ -5 -15]]


In [5]:
myMatrix4 = np.matmul(myMatrix1, myMatrix2) # or equivalently myMatrix1 @ myMatrix2
print(myMatrix4)

[[21 27]
 [20 33]]


In [7]:
print(myMatrix4[1,0])
print(myMatrix3[0,:])
print(myMatrix4[:,1])

20
[-1  0]
[27 33]


In [8]:
myMatrix5 = np.copy(myMatrix4)
myMatrix5[0,:] = myMatrix5[0,:]/3
print(myMatrix5)

[[ 7  9]
 [20 33]]


In [9]:
myMatrix5[1,:] = myMatrix5[1,:] - 2*myMatrix5[0,:]
print(myMatrix5)

[[ 7  9]
 [ 6 15]]


In [10]:
myMatrix6 = np.copy(myMatrix4)
myMatrix6[[0, 1],:] = myMatrix6[[1, 0],:]
print(myMatrix6)

[[20 33]
 [21 27]]


In [ ]:
myMatrix1_fl = np.array([[1, 4], [5, 3]], dtype=float) # or myMatrix1_fl = np.array([[1., 4.], [5., 3.]])
print(myMatrix1_fl)

[[1. 4.]
 [5. 3.]]
