In [1]:
import numpy as np
from scipy import linalg

In [2]:
def P_matrix(B, B_prime):
    """ Computes the P matrix of change in coordinates. """
    P = linalg.inv(B_prime) @ B
    return(P)

def coord_trans_vector(vec, P):
    """ Transforms the coordinates of a vector. """
    trans_vec = linalg.inv(P) @ vec
    return(trans_vec)

In [ ]:
B1 = np.array([[1.,  1.], 
              [2., -1.]])

P1 = P_matrix(B1, np.identity(2))
old_v = np.array([2., 1.])
new_v = coord_trans_vector(old_v, P1)
print(new_v)

[1. 1.]


In [4]:
def coord_trans_matrix(A, P):
    """ Transforms the coordinates of a matrix. """
    trans_matrix = linalg.inv(P) @ A @ P
    return(trans_matrix)


In [6]:
B2 = np.array([[2., -1.], 
             [-1.,  1.]])
old_A = np.array([[1.,  1.], 
              [0.,  1.]])

P2 = P_matrix(B2, np.identity(2))
new_A = coord_trans_matrix(old_A, P2)
print(new_A)

[[ 0.  1.]
 [-1.  2.]]


In [7]:
A = np.array([[1.,  1.,  3.],
              [2., -1., -1.],
              [2.,  0.,  1.],])
Q, R = linalg.qr(A)
print("Q = ", Q)
print("R = ", R)

Q =  [[-0.33333333  0.80845208 -0.48507125]
 [-0.66666667 -0.56591646 -0.48507125]
 [-0.66666667  0.16169042  0.72760688]]
R =  [[-3.          0.33333333 -1.        ]
 [ 0.          1.37436854  3.15296313]
 [ 0.          0.         -0.24253563]]
