In [1]:
import numpy as np
from scipy import linalg

In [2]:
A1 = np.array([[4, 2, 0],
               [2, 2, 2],
               [0, 2, 5]])
print(linalg.cholesky(A1))

[[2. 1. 0.]
 [0. 1. 2.]
 [0. 0. 1.]]


In [3]:
A2 = np.array([[1, 1, 2],
               [2, 2, 3],
               [1, 3, 0]])
P, L, U_raw = linalg.lu(A2)
D = np.diag(np.diag(U_raw)) # Factor out the diagonal elements in U_raw
U = U_raw/np.diag(U_raw)[:,None]
print(P, L, D, U)
print(np.allclose(P@L@D@U, A2)) # Check if the factors can be combined to reconstruct the matrix

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] [[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.  1. ]] [[2.  0.  0. ]
 [0.  2.  0. ]
 [0.  0.  0.5]] [[ 1.    1.    1.5 ]
 [ 0.    1.   -0.75]
 [ 0.    0.    1.  ]]
True


In [4]:
A3 = np.array([[1, 1, 0, 1],
               [1,-1, 1, 0],
               [2, 0, 1, 1]])
U, Sigma, V_H = linalg.svd(A3)
print(U, Sigma, V_H)

[[-4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.16496581e-01  2.22044605e-16  5.77350269e-01]] [3.00000000e+00 1.73205081e+00 9.06493304e-17] [[-8.16496581e-01 -1.11022302e-16 -4.08248290e-01 -4.08248290e-01]
 [ 2.22044605e-16 -8.16496581e-01  4.08248290e-01 -4.08248290e-01]
 [-4.82329146e-02 -5.75332008e-01 -5.27099093e-01  6.23564922e-01]
 [-5.75332008e-01  4.82329146e-02  6.23564922e-01  5.27099093e-01]]


In [5]:
print(linalg.pinv(A3))

[[ 1.11111111e-01  1.11111111e-01  2.22222222e-01]
 [ 3.33333333e-01 -3.33333333e-01 -7.44563871e-17]
 [-1.11111111e-01  2.22222222e-01  1.11111111e-01]
 [ 2.22222222e-01 -1.11111111e-01  1.11111111e-01]]


In [6]:
h = np.array([1, 1, 1])
print(linalg.pinv(A3) @ h)
print(linalg.lstsq(A3, h))  

[ 4.44444444e-01 -2.96500992e-16  2.22222222e-01  2.22222222e-01]
(array([ 4.44444444e-01, -5.55111512e-17,  2.22222222e-01,  2.22222222e-01]), array([], dtype=float64), 2, array([3.00000000e+00, 1.73205081e+00, 9.61481343e-17]))
